# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Menu
menu:
  é¦– é¡µ: / || icon-shouye-01 || fas fa-tasks || faa-tada
  æ–‡ ç« ||icon-wenzhang:
    åˆ† ç±»: /articals/categories/ || icon-fenlei2 || faa-tada
    å½’ æ¡£: /articals/archives/ || icon-guidang || fas fa-archives
    æ ‡ ç­¾: /articals/tags/ || icon-biaoqian || fas fa-tags
  ä¼‘ é—²||icon-yule:
    éŸ³ ä¹: /relax/music/ || icon-yinle || fa fa-camera || faa-tada
    å½± è§†: /relax/video/ || icon-dianying || fas fa-video
  ç©º é—´ || icon-kongjian1:
    LoveStory: /zone/love-story/ || icon-guanai-aixin
    Work&Life: /zone/work-life/ || icon-shenghuo
  ç¤¾ äº¤ || icon-guanyuwomen:
    ç•™ è¨€ æ¿: /social/comments/ || icon-xiangsufeng_xinfeng || fas fa-envelope
    Friends: /social/link/ || icon-lianjie || fas fa-link
  About: /about/ || icon-guanyu

# ä»£ç å—ç›¸å…³é…ç½®
highlight_theme: mac # darker # pale night # light # ocean # mac # mac light
highlight_copy: true # å…è®¸ä»£ç è¢«å¤åˆ¶
highlight_shrink: false # ä»£ç å—é»˜è®¤æŠ˜å 
code_word_wrap: true # ä»£ç æ¢è¡Œ
highlight_height_limit: false # unit: px é™åˆ¶ä»£ç å—æœ€å¤§æ˜¾ç¤ºé«˜åº¦

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_img:
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/

# æ–‡ç« é»˜è®¤å°é¢
## å¯åœ¨æ–‡ç« çš„front-matteré‡Œå•ç‹¬è®¾ç½® cover: xxx.jpg æ¥è¦†ç›–é»˜è®¤å°é¢
cover:
  # æ˜¯å¦æ˜¾ç¤ºæ–‡ç« å°é¢
  index_enable: true # åœ¨é¦–é¡µä¸­æ˜¾ç¤ºæ–‡ç« å°é¢
  aside_enable: true # ä¾§è¾¹æ˜¾ç¤ºæ–‡ç« å°é¢
  archives_enable: true # å½’æ¡£ä¸­æ˜¾ç¤ºæ–‡ç« å°é¢
  # å°é¢æ˜¾ç¤ºçš„ä½ç½®
  # ä¸‰ä¸ªå€¼å¯é…ç½® left , right , both
  position: both
  # å½“æ²¡æœ‰è®¾ç½®coveræ—¶ï¼Œé»˜è®¤çš„å°é¢æ˜¾ç¤º
  ## å¯ä»¥å†™åˆ—è¡¨æ”¾å¤šå¼ å›¾ç‰‡ï¼Œç³»ç»Ÿä¼šéšæœºé€‰å–ä¹‹ä¸€
  default_cover: https://blog.onlyy.vip/img/Wendy.png

# æ–‡ç« å…ƒä¿¡æ¯
post_meta:
  page:
    date_type: both # created or updated or both ä¸»é¡µæ–‡ç« æ—¥æœŸæ˜¯åˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½æ˜¾ç¤º
    date_format: date # date/relative æ˜¾ç¤ºæ—¥æœŸè¿˜æ˜¯ç›¸å¯¹æ—¥æœŸ
    categories: true # true or false ä¸»é¡µæ˜¯å¦æ˜¾ç¤ºåˆ†ç±»
    tags: true # true or false ä¸»é¡µæ˜¯å¦æ˜¾ç¤ºæ ‡ç­¾
    label: true # true or false æ˜¾ç¤ºæè¿°æ€§æ–‡å­—
  post:
    date_type: both # created or updated or both æ–‡ç« é¡µæ—¥æœŸæ˜¯åˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½æ˜¾ç¤º
    date_format: date # date/relative æ˜¾ç¤ºæ—¥æœŸè¿˜æ˜¯ç›¸å¯¹æ—¥æœŸ
    categories: true # true or false æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤ºåˆ†ç±»
    tags: true # true or false æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤ºæ ‡ç­¾
    label: true # true or false æ˜¾ç¤ºæè¿°æ€§æ–‡å­—

# æ–‡ç« ç‰ˆæƒä¿¡æ¯
post_copyright:
  enable: true
  decode: true
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  copyright_author: ChrisLey
  copyright_info: æ­¤æ–‡ç« ç‰ˆæƒå½’ChrisLeyæ‰€æœ‰, å¦‚æœ‰è½¬è½½, è¯·æ³¨æ˜æ¥è‡ªåŸä½œè€…

# æ–‡ç« æ‰“èµä¿¡æ¯
reward:
  enable: true
  coinAudio: https://assets.akilar.top@1.0.16/audio/coin.mp3
  QR_code:
    - img: /img/wechat.jpg
      link:
      text: å¾® ä¿¡
    - img: /img/alipay.jpg
      link:
      text: æ”¯ä»˜å®
  CDN:
    # main
    main_css: /css/index.css
    jquery: https://npm.elemecdn.com/jquery@latest/dist/jquery.min.js
    main: /js/main.js
    utils: /js/utils.js
    # æ‰“èµæŒ‰é’®æŠ•å¸æ•ˆæœ
    coin_js: /js/coin.js
    coin_css: /css/coin.css

# æ–‡ç« ç›®å½• toc
toc:
  priority: 1
  post: true # æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤º TOC
  page: true # æ™®é€šé¡µé¢æ˜¯å¦æ˜¾ç¤º TOC
  number: true # æ˜¯å¦æ˜¾ç¤ºç« èŠ‚æ•°
  expand: false # æ˜¯å¦å±•å¼€ TOC
  style_simple: false # for post ç®€æ´æ¨¡å¼ï¼ˆä¾§è¾¹æ åªæ˜¾ç¤º TOC, åªå¯¹æ–‡ç« é¡µæœ‰æ•ˆ ï¼‰

# ç›¸å…³æ–‡ç«  æ ¹æ® tags æƒé‡æ¨è
related_post:
  enable: true
  limit: 6 # æ˜¾ç¤ºæ¨èæ–‡ç« æ•°ç›®
  date_type: created # or created or updated æ–‡ç« æ—¥æœŸæ˜¾ç¤ºåˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥

# æ–‡ç« é”šç‚¹
# anchor
# when you scroll in post , the url will update according to header id.
anchor: true

# æ–‡ç« åˆ†é¡µ
# post_pagination
# false:ä¸ºå…³é—­åˆ†é¡µæŒ‰é’®ï¼›1:ä¸‹ä¸€ç¯‡æ˜¾ç¤ºçš„æ˜¯æ—§æ–‡ç« ï¼›2:ä¸‹ä¸€ç¯‡æ˜¾ç¤ºçš„æ˜¯æ–°æ–‡ç« 
# 1: The 'next post' will link to old post
# 2: The 'next post' will link to new post
# false: disable pagination
post_pagination: 2

# Displays outdated notice for a post (æ–‡ç« è¿‡æœŸæé†’)
noticeOutdate:
  enable: true
  style: flat # style: simple/flat
  limit_day: 365 # è·ç¦»æ›´æ–°æ—¶é—´å¤šå°‘å¤©æ‰æ˜¾ç¤ºæ–‡ç« è¿‡æœŸæé†’
  position: top # position: top/bottom
  message_prev: è¿™ç¯‡æ–‡ç« å†™äº # å¤©æ•°ä¹‹å‰çš„æ–‡å­—
  message_next: å¤©ä¹‹å‰ï¼Œå†…å®¹å¯èƒ½æœ‰ç‚¹æ—§äº†å“¦ã€‚ # å¤©æ•°ä¹‹åçš„æ–‡å­—

# ä¸ªäººä¿¡æ¯
## å¤´åƒ
avatar:
  img: /img/avatar.png
  effect: false # æ˜¯å¦å¼€å¯æ—‹è½¬åŠ¨ç”»infinity

## ç¤¾äº¤ä¸»é¡µ
social:
  Github: https://github.com/loveyy520 || icon-github1
  Email: mailto:201357337@qq.com || icon-email

# æ–‡ç« å¤åˆ¶é…ç½®
# copy settings
# copyright: Add the copyright information after copied content (å¤åˆ¶çš„å†…å®¹åé¢åŠ ä¸Šç‰ˆæƒä¿¡æ¯)
copy:
  enable: true # æ˜¯å¦å¼€å¯ç½‘ç«™å¤åˆ¶æƒé™
  copyright: # å¤åˆ¶çš„å†…å®¹åé¢åŠ ä¸Šç‰ˆæƒä¿¡æ¯
    enable: true # æ˜¯å¦å¼€å¯å¤åˆ¶ç‰ˆæƒä¿¡æ¯æ·»åŠ 
    limit_count: 50 # å­—æ•°é™åˆ¶ï¼Œå½“å¤åˆ¶æ–‡å­—å¤§äºè¿™ä¸ªå­—æ•°é™åˆ¶æ—¶ï¼Œå°†åœ¨å¤åˆ¶çš„å†…å®¹åé¢åŠ ä¸Šç‰ˆæƒä¿¡æ¯

# é¡µè„šè®¾ç½®
footer:
  owner:
    enable: true
    since: 2022 # ç«™ç‚¹èµ·å§‹æ—¶é—´
    # æ˜¯ä¸€ä¸ªç»™ä½ ç”¨æ¥åœ¨é¡µè„šè‡ªå®šä¹‰æ–‡æœ¬çš„é€‰é¡¹ã€‚é€šå¸¸ä½ å¯ä»¥åœ¨è¿™é‡Œå†™å£°æ˜æ–‡æœ¬ç­‰,æ”¯æŒ HTMLã€‚
    custom_text: I wish you to become your own sun, no need to rely on who's light.<p><a target="_blank" href="https://hexo.io/"><img src="https://img.shields.io/badge/Frame-Hexo-blue?style=flat&logo=hexo" title="åšå®¢æ¡†æ¶ä¸ºHexo"></a>&nbsp;<a target="_blank" href="https://butterfly.js.org/"><img src="https://img.shields.io/badge/Theme-Butterfly-6513df?style=flat&logo=bitdefender" title="ä¸»é¢˜é‡‡ç”¨butterfly"></a>&nbsp;<a target="_blank" href="https://www.jsdelivr.com/"><img src="https://img.shields.io/badge/CDN-jsDelivr-orange?style=flat&logo=jsDelivr" title="æœ¬ç«™ä½¿ç”¨JsDelivrä¸ºé™æ€èµ„æºæä¾›CDNåŠ é€Ÿ"></a> &nbsp;<a target="_blank" href="https://vercel.com/ "><img src="https://img.shields.io/badge/Hosted-Vervel-brightgreen?style=flat&logo=Vercel" title="æœ¬ç«™é‡‡ç”¨åŒçº¿éƒ¨ç½²ï¼Œé»˜è®¤çº¿è·¯æ‰˜ç®¡äºVercel"></a>&nbsp;<a target="_blank" href="https://vercel.com/ "><img src="https://img.shields.io/badge/Hosted-Coding-0cedbe?style=flat&logo=Codio" title="æœ¬ç«™é‡‡ç”¨åŒçº¿éƒ¨ç½²ï¼Œè”é€šçº¿è·¯æ‰˜ç®¡äºCoding"></a>&nbsp;<a target="_blank" href="https://github.com/"><img src="https://img.shields.io/badge/Source-Github-d021d6?style=flat&logo=GitHub" title="æœ¬ç«™é¡¹ç›®ç”±Gtihubæ‰˜ç®¡"></a>&nbsp;<a target="_blank" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://img.shields.io/badge/Copyright-BY--NC--SA%204.0-d42328?style=flat&logo=Claris" title="æœ¬ç«™é‡‡ç”¨çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº«4.0å›½é™…è®¸å¯åè®®è¿›è¡Œè®¸å¯"></a></p>
  copyright: false # Copyright of theme and framework

# å³ä¸‹è§’
## ç¹ç®€è¯­è¨€
translate:
  enable: false
  # é»˜è®¤æŒ‰é’®æ˜¾ç¤ºæ–‡å­—(ç½‘ç«™æ˜¯ç®€ä½“ï¼Œåº”è®¾ç½®ä¸º'default: ç¹')
  default: ç¹
  # the language of website (1 - Traditional Chinese/ 2 - Simplified Chineseï¼‰
  # ç½‘ç«™é»˜è®¤è¯­è¨€ï¼Œ1: ç¹ä½“ä¸­æ–‡, 2: ç®€ä½“ä¸­æ–‡
  defaultEncoding: 2
  # Time delay å»¶è¿Ÿæ—¶é—´,è‹¥ä¸åœ¨å‰, è¦è®¾å®šå»¶è¿Ÿç¿»è¯‘æ—¶é—´, å¦‚100è¡¨ç¤º100ms,é»˜è®¤ä¸º0
  translateDelay: 0
  # å½“æ–‡å­—æ˜¯ç®€ä½“æ—¶ï¼ŒæŒ‰é’®æ˜¾ç¤ºçš„æ–‡å­—
  msgToTraditionalChinese: "ç¹"
  # å½“æ–‡å­—æ˜¯ç¹ä½“æ—¶ï¼ŒæŒ‰é’®æ˜¾ç¤ºçš„æ–‡å­—
  msgToSimplifiedChinese: "ç°¡"

## å¤œé—´æ¨¡å¼
# dark mode
darkmode:
  enable: false
  # dark å’Œ light ä¸¤ç§æ¨¡å¼åˆ‡æ¢æŒ‰é’®
  button: true
  # Switch dark/light mode automatically (è‡ªå‹•åˆ‡æ› dark modeå’Œ light mode)
  # autoChangeMode: 1  Following System Settings, if the system doesn't support dark mode, it will switch dark mode between 6 pm to 6 am
  # autoChangeMode: 2  Switch dark mode between 6 pm to 6 am
  # autoChangeMode: false
  autoChangeMode: false

## é˜…è¯»æ¨¡å¼
readmode: true

# ä¾§è¾¹æ è®¾ç½®
##
aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  display:
    archive: true
    tag: true
    category: true
  ### ä½œè€…ä¿¡æ¯å¡ç‰‡
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: # fab fa-github
      text: ğŸ›´Have a look...
      link: https://github.com/loveyy520
  card_announcement:
    enable: false
    content: <center>ä¸»åŸŸåï¼š<br><a href="https://loveyy520.github.io/onlyy-blog"><b><font color="#5ea6e5">loveyy520.github.io</font></b></a>&nbsp;|&nbsp;<a href="https://blog.onlyy.vip"><b><font color="#5ea6e5">blog.onlyy.vip</font></b></a><br><a href="mailto:201357337@qq.com@fomal.cn">ğŸ“¬ï¼š<b><font color="#a591e0">201357337@qq.com</font></b></a></center>
    exclude:
      - /post/
  ### è¿‘æœŸæ–‡ç« 
  card_recent_post:
    enable: true
    limit: 3 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
    exclude:
      - /post/
  ### åˆ†ç±»
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
    exclude:
      - /post/
  card_tags:
    enable: true
    limit: 20 # if set 0 will show all
    color: true
    sort_order: # Don't modify the setting unless you know how it works
    exclude:
      - /post/
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYYå¹´MMæœˆ
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
    exclude:
      - /post/
  card_webinfo:
    enable: false
    post_count: true
    last_push_date: true
    sort_order: # Don't modify the setting unless you know how it works
    exclude:
      - /post/
  # å¾®åšçƒ­æœ
  card_weibo:
    enable: false
    exclude:
      - /post/

## UV / PV
busuanzi:
  site_uv: true # æœ¬ç«™æ€»è®¿å®¢æ•°
  site_pv: true # æœ¬ç«™æ€»è®¿é—®é‡
  page_pv: true # æœ¬æ–‡æ€»é˜…è¯»é‡

## è¿è¡Œæ—¶é—´
# Time difference between publish date and now (ç¶²é é‹è¡Œæ™‚é–“)
# Formal: Month/Day/Year Time or Year/Month/Day Time
runtimeshow:
  enable: false
  publish_date: 2022/10/30 00:00:00
  ##ç½‘é¡µå¼€é€šæ—¶é—´
  #æ ¼å¼: æœˆ/æ—¥/å¹´ æ—¶é—´
  #ä¹Ÿå¯ä»¥å†™æˆ å¹´/æœˆ/æ—¥ æ—¶é—´
# æœ€æ–°è¯„è®ºä¿¡æ¯
# Aside widget - Newest Comments
# newest_comments:
#   enable: true
#   sort_order: # Don't modify the setting unless you know how it works
#   limit: 6  # æ˜¾ç¤ºçš„æ•°é‡
#   storage: 10 # è®¾ç½®ç¼“å­˜æ—¶é—´ï¼Œå•ä½ åˆ†é’Ÿ
#   avatar: true # æ˜¯å¦æ˜¾ç¤ºå¤´åƒ

## ç½‘ç«™èƒŒæ™¯å›¾
# å›¾ç‰‡æ ¼å¼ url(http://xxxxxx.com/xxx.jpg)
# é¢œè‰²ï¼ˆHEXå€¼/RGBå€¼/é¢œè‰²å•è¯/æ¸å˜è‰²)
# ç•™ç©º ä¸æ˜¾ç¤ºèƒŒæ™¯
background: url(https://blog.onlyy.vip/img/Wendy.png)

## æ‰“å­—æœºæ•ˆæœ
# Typewriter Effect (æ‰“å­—æ•ˆæœ)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: false
  colorful: true # open particle animation (å†’å…‰ç‰¹æ•ˆ)
  shake: true #  open shake (æŠ–å‹•ç‰¹æ•ˆ)
  mobile: false

## é¡µè„šèƒŒæ™¯å›¾
# footeræ˜¯å¦æ˜¾ç¤ºå›¾ç‰‡èƒŒæ™¯(trueä¸ºä¸top_imgä¸€è‡´)
footer_bg: false

## èƒŒæ™¯ç‰¹æ•ˆ
### åŠ¨æ€
canvas_fluttering_ribbon:
  enable: true
  mobile: true # false æ‰‹æœºç«¯ä¸æ˜¾ç¤º true æ‰‹æœºç«¯æ˜¾ç¤º
### é™æ€
# canvas_ribbon:
#   enable: false
#   size: 150
#   alpha: 0.6
#   zIndex: -1
#   click_to_change: false #è¨­ç½®æ˜¯å¦æ¯æ¬¡é»æ“Šéƒ½æ›´æ›å½©å¸¦
#   mobile: false # false æ‰‹æ©Ÿç«¯ä¸é¡¯ç¤º true æ‰‹æ©Ÿç«¯é¡¯ç¤º
### canvasè¯¦ç»†è®¾ç½®
# canvas_nest:
#   enable: true
#   color: "0,0,255" #color of lines, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
#   opacity: 0.7 # the opacity of line (0~1), default: 0.5.
#   zIndex: -1 # z-index property of the background, default: -1.
#   count: 99 # the number of lines, default: 99.
#   mobile: false # false æ‰‹æ©Ÿç«¯ä¸é¡¯ç¤º true æ‰‹æ©Ÿç«¯é¡¯ç¤º

## ç‚¹å‡»ç‰¹æ•ˆ
### çƒŸèŠ±
# fireworks:
#   enable: true
#   zIndex: 9999 # -1 or 9999
#   mobile: false
### çˆ±å¿ƒ
click_heart:
  enable: true
  mobile: false
### è‡ªå®šä¹‰æ–‡å­—
# ClickShowText:
#   enable: false
#   #### æ¯æ¬¡ç‚¹å‡»å‡ºç°åˆ—è¡¨éšæœºä¸€é¡¹
#   text:
#     - I
#     - LOVE
#     - YOU
#   fontSize: 15px
#   random: false # æ–‡å­—éšæœºæ˜¾ç¤º
#   mobile: false

# å­—ä½“é…ç½®
## å…¨å±€å­—ä½“
# Global font settings
# Don't modify the following settings unless you know how they work (éå¿…è¦ä¸è¦ä¿®æ”¹)
font:
  global-font-size: "15px"
  code-font-size: "14px"
  # -apple-system, BlinkMacSystemFont, "Segoe UI" , "Helvetica Neue" , Lato, Roboto, "PingFang SC" , "Microsoft JhengHei" , "Microsoft YaHei" , sans-serif
  # Wenkai, consolas, -apple-system, 'Quicksand', 'Nimbus Roman No9 L', 'PingFang SC', 'Hiragino Sans GB', 'Noto Serif SC', 'Microsoft Yahei', 'WenQuanYi Micro Hei', 'ST Heiti', sans-serif;
  font-family: var(--global-font), Consolas_1, -apple-system, 'Quicksand', 'Nimbus Roman No9 L', 'PingFang SC', 'Hiragino Sans GB', 'Noto Serif SC', 'Microsoft Yahei', 'WenQuanYi Micro Hei', 'ST Heiti', sans-serif;
  # consolas, ZhuZiAWan_light, "Microsoft YaHei", Menlo, "PingFang SC", "Microsoft JhengHei", sans-serif
  # Consolas_1, ZhuZiAWan_light, "Microsoft YaHei", Menlo, "PingFang SC", "Microsoft JhengHei", sans-serif
  code-font-family: Consolas_1, var(--global-font), "Microsoft YaHei", Menlo, "PingFang SC", "Microsoft JhengHei", sans-serif
## æ ‡é¢˜å­—ä½“
# Font settings for the site title and site subtitle
# https://fonts.googleapis.com/css?family=Titillium+Web&display=swap
# Titillium Web, 'PingFang SC' , 'Hiragino Sans GB' , 'Microsoft JhengHei' , 'Microsoft YaHei' , sans-serif
# å·¦ä¸Šè§’ç¶²ç«™åå­— ä¸»é å±…ä¸­ç¶²ç«™åå­—
blog_title_font:
  font_link:
  font-family: var(--global-font)

# Subtitle
# the subtitle on homepage (ä¸»é subtitle)
subtitle:
  enable: true
  # Typewriter Effect (æ‰“å­—æ•ˆæœ)
  effect: true
  # loop (å¾ªç’°æ‰“å­—)
  loop: true
  # source èª¿ç”¨ç¬¬ä¸‰æ–¹æœå‹™
  # source: false é—œé–‰èª¿ç”¨
  # source: 1  èª¿ç”¨ä¸€è¨€ç¶²çš„ä¸€å¥è©±ï¼ˆç°¡é«”ï¼‰ https://hitokoto.cn/
  # source: 2  èª¿ç”¨ä¸€å¥ç¶²ï¼ˆç°¡é«”ï¼‰ http://yijuzhan.com/
  # source: 3  èª¿ç”¨ä»Šæ—¥è©©è©ï¼ˆç°¡é«”ï¼‰ https://www.jinrishici.com/
  # subtitle æœƒå…ˆé¡¯ç¤º source , å†é¡¯ç¤º sub çš„å…§å®¹
  source: false
  # å¦‚æœé—œé–‰æ‰“å­—æ•ˆæœï¼Œsubtitle åªæœƒé¡¯ç¤º sub çš„ç¬¬ä¸€è¡Œæ–‡å­—
  sub:
    - "Onlyy with you!ğŸ¥"
    - "Wish u have fun!ğŸ­ğŸ­ğŸ­"

# åŠ è½½åŠ¨ç”» Loading Animation
preloader: true

# å­—æ•°ç»Ÿè®¡
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

# å›¾ç‰‡æŸ¥çœ‹å¤§å›¾
# fancybox http://fancyapps.com/fancybox/3/
fancybox: true

# æ³¨å…¥è‡ªå®šä¹‰å†…å®¹: ä¸€èˆ¬ head é‡Œæ”¾ style è€Œåœ¨ bottom æ”¾ script
# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# æ’å…¥ä»£ç åˆ°å¤´éƒ¨ </head> ä¹‹å‰ å’Œ åº•éƒ¨ </body> ä¹‹å‰
inject:
  head:
    - <link rel="stylesheet" href="https://blog.onlyy.vip/css/custom.css">
  bottom:
    # iconfont
    - <script async src="//at.alicdn.com/t/c/font_3751481_rphep3klel.js"></script> # iconfont onlyy-blog
    # åŠ è½½è¿›åº¦æ¡
    - <script src="https://blog.onlyy.vip/assets/scripts/progress-bar.js"></script>
    # éŸ³ä¹æ’­æ”¾å™¨ data-server ç”¨çš„ç½‘æ˜“äº‘ netease / è…¾è®¯åˆ™ tencent
    # - <div class="aplayer no-destroy" data-id="60198" data-server="netease" data-type="playlist" data-fixed="true" data-autoplay="false"> </div>

# algolia search
algolia_search:
  enable: false
  hits:
    per_page: 6

# æœ¬åœ°æœç´¢é…ç½®
local_search:
  enable: true

# ç¾åŒ–
beautify:
  enable: true
  field: post # site/post
  # title-prefix-icon: '\f0c1' åŸå†…å®¹
  title-prefix-icon: '\f863'
  title-prefix-icon-color: "#F47466"

# é¡µè„šç¾åŒ–
# footer_beautify
# é¡µè„šè®¡æ—¶å™¨ï¼š[Native JS Timer](https://akilar.top/posts/b941af/)
# é¡µè„šå¾½æ ‡ï¼š[Add Github Badge](https://akilar.top/posts/e87ad7f8/)
footer_beautify:
  enable:
    timer: true # è®¡æ—¶å™¨å¼€å…³
    bdage: true # å¾½æ ‡å¼€å…³
  priority: 5 # è¿‡æ»¤å™¨ä¼˜å…ˆæƒ
  enable_page: all # åº”ç”¨é¡µé¢
  # å±è”½é¡µé¢
  exclude:
    # - /posts/
    # - /about/
  layout: # æŒ‚è½½å®¹å™¨ç±»å‹
    type: id
    name: footer-wrap
    index: 0
  # è®¡æ—¶å™¨éƒ¨åˆ†é…ç½®é¡¹ï¼ˆçœ‹ä½ å–œæ¬¢å“ªä¸ªï¼Œæœ€å¥½ä¸‹è½½ä¸‹æ¥æ”¾åˆ°è‡ªå·±çš„é¡¹ç›®ä¸­ä¸ç„¶ä¼šå¢åŠ æˆ‘ç½‘ç«™çš„è´Ÿè½½ï¼‰
  # è¿™æ˜¯æˆ‘çš„
  runtime_js: https://blog.onlyy.vip/assets/scripts/footerTimer.js
  runtime_css: https://blog.onlyy.vip/css/footerTimer.css
  # è¿™æ˜¯åº—é•¿çš„
  # runtime_js: https://npm.elemecdn.com/hexo-butterfly-footer-beautify@1.0.0/lib/runtime.js
  # runtime_css: https://npm.elemecdn.com/hexo-butterfly-footer-beautify@1.0.0/lib/runtime.css
  # å¾½æ ‡éƒ¨åˆ†é…ç½®é¡¹
  swiperpara: 0 # è‹¥é0ï¼Œåˆ™å¼€å¯è½®æ’­åŠŸèƒ½ï¼Œæ¯è¡Œå¾½æ ‡ä¸ªæ•°
  bdageitem:
    - link: https://hexo.io/ # å¾½æ ‡æŒ‡å‘ç½‘ç«™é“¾æ¥
      shields: https://img.shields.io/badge/Frame-Hexo-blue?style=flat&logo=hexo # å¾½æ ‡API
      message: åšå®¢æ¡†æ¶ä¸ºHexo_v6.2.0 # å¾½æ ‡æç¤ºè¯­
    - link: https://butterfly.js.org/
      shields: https://img.shields.io/badge/Theme-Butterfly-6513df?style=flat&logo=bitdefender
      message: ä¸»é¢˜ç‰ˆæœ¬Butterfly_v4.5.1
    - link: https://vercel.com/
      shields: https://img.shields.io/badge/Hosted-Vercel-brightgreen?style=flat&logo=Vercel
      message: æœ¬ç«™é‡‡ç”¨å¤šçº¿éƒ¨ç½², ä¸»çº¿è·¯æ‰˜ç®¡äºVercel
    - link: https://github.com/
      shields: https://img.shields.io/badge/Source-Github-d021d6?style=flat&logo=GitHub
      message: æœ¬ç«™é¡¹ç›®ç”±Githubæ‰˜ç®¡
    - link: http://creativecommons.org/licenses/by-nc-sa/4.0/
      shields: https://img.shields.io/badge/Copyright-BY--NC--SA%204.0-d42328?style=flat&logo=Claris
      message: æœ¬ç«™é‡‡ç”¨çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº«4.0å›½é™…è®¸å¯åè®®è¿›è¡Œè®¸å¯
  swiper_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.css
  swiper_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.js
  swiperbdage_init_js: https://npm.elemecdn.com/hexo-butterfly-footer-beautify/lib/swiperbdage_init.min.js

# éŸ³ä¹æ’­æ”¾å™¨è®¾ç½®
# Inject the css and script (aplayer/meting)
aplayerInject:
  enable: true
  per_page: true
