# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# å­—ä½“å›¾æ ‡å¤‡é€‰
# ğŸ¦„ğŸ¦‹ğŸŒ¿ğŸ•¸â„ï¸ğŸ’ğŸ­ğŸ·âœ…ââ—ï¸

# Site
title: OnlyyğŸ¦„
subtitle: ""
description: "Record of life ğŸ·"
keywords:
author: ChrisLeyâ„ï¸
language: zh-CN
timezone: "Asia/Shanghai"

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.onlyy.vip/
root: /
permalink: articals/:abbrlink/
permalink_defaults:
# abbrlink config
abbrlink:
  alg: crc32 #support crc16(default) and crc32
  rep: hex #support dec(default) and hex
  drafts: false #(true)Process draft,(false)Do not process draft. false(default)
  # Generate categories from directory-tree
  # depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
    enable: true #true(default)
    depth: #3(default)
    over_write: false
  auto_title: false #enable auto title, it can auto fill the title by path
  auto_date: false #enable auto date, it can auto fill the date by time today
  force: false #enable force mode,in this mode, the plugin will ignore the cache, and calc the abbrlink for every post even it already had abbrlink. This only updates abbrlink rather than other front variables.

pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: articals/tags
archive_dir: articals/archives
category_dir: articals/categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# ç»™å½’æ¡£ æ¢ä¸ª åå­—
archive_title: æ—¶å…‰æœºğŸ­

# æ–‡ç« è®¾ç½®
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
auto_spacing: true
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
marked: # ! embed an image in markdown of hexo-renderer-marked 3.1.0
  prependRoot: true
  postAsset: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# éƒ¨ç½²
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:loveyy520/onlyy-blog.git
  # repo: https://github.com/loveyy520/onlyy-blog.git #https://bitbucket.org/JohnSmith/johnsmith.bitbucket.io
  branch: main
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"

# æœç´¢
search:
  path: search.xml
  field: post
  content: true

# å‰ç«¯è·¯ç”±
# Pjax [Beta]
# It may contain bugs and unstable, give feedback when you find the bugs.
# https://github.com/MoOx/pjax
pjax:
  enable: true
  # å¯¹äºä¸€äº›ç¬¬ä¸‰æ–¹æ’ä»¶ï¼Œæœ‰äº›å¹¶ä¸æ”¯æŒ pjax ã€‚
  # ä½ å¯ä»¥æŠŠç½‘é¡µåŠ å…¥åˆ° exclude é‡Œï¼Œè¿™ä¸ªç½‘é¡µä¼šè¢« pjax æ’é™¤åœ¨å¤–ã€‚
  # ç‚¹å‡»è¯¥ç½‘é¡µä¼šé‡æ–°åŠ è½½ç½‘ç«™ã€‚
  exclude:
    - /music/
    - /video/

# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true # å¼€å…³æ’ä»¶ç‰ˆçœ‹æ¿å¨˜
  scriptFrom: local # é»˜è®¤
  pluginRootPath: live2dw/ # æ’ä»¶åœ¨ç«™ç‚¹ä¸Šçš„æ ¹ç›®å½•(ç›¸å¯¹è·¯å¾„)
  pluginJsPath: lib/ # è„šæœ¬æ–‡ä»¶ç›¸å¯¹ä¸æ’ä»¶æ ¹ç›®å½•è·¯å¾„
  pluginModelPath: assets/ # æ¨¡å‹æ–‡ä»¶ç›¸å¯¹ä¸æ’ä»¶æ ¹ç›®å½•è·¯å¾„
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://npm.elemecdn.com/live2d-widget@3.x/lib/L2Dwidget.min.js # ä½ çš„è‡ªå®šä¹‰ url
  tagMode: false # æ ‡ç­¾æ¨¡å¼, æ˜¯å¦ä»…æ›¿æ¢ live2d tagæ ‡ç­¾è€Œéæ’å…¥åˆ°æ‰€æœ‰é¡µé¢ä¸­
  debug: false # è°ƒè¯•, æ˜¯å¦åœ¨æ§åˆ¶å°è¾“å‡ºæ—¥å¿—
  model:
    ## éœ€è¦å®‰è£…å¯¹åº”çš„æ¨¡å‹ live2d-widget-model-shizuku / live2d-widget-model-nico
    # use: live2d-widget-model-shizuku # npm-module package name
    use: shizuku # æ ¹ç›®å½•/live2d_models/ ä¸‹çš„ç›®å½•å
    # use: ./wives/wanko # ç›¸å¯¹äºåšå®¢æ ¹ç›®å½•çš„è·¯å¾„
    # use: https://npm.elemecdn.com/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # ä½ çš„è‡ªå®šä¹‰ url
  display:
    position: left #æ§åˆ¶çœ‹æ¿å¨˜ä½ç½®
    width: 150 #æ§åˆ¶çœ‹æ¿å¨˜å¤§å°
    height: 300 #æ§åˆ¶çœ‹æ¿å¨˜å¤§å°
  mobile:
    show: true # æ‰‹æœºä¸­æ˜¯å¦å±•ç¤º

# envelope_comment
# see https://akilar.top/posts/e2d3c450/
envelope_comment:
  enable: true #æ§åˆ¶å¼€å…³
  custom_pic:
    # cover: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/violet.jpg # ä¿¡ç¬ºå¤´éƒ¨å›¾ç‰‡
    cover: https://assets.onlyy.vip/photos/dont-starve/bg_wendy_victorian.png
    line: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/line.png # ä¿¡ç¬ºåº•éƒ¨å›¾ç‰‡
    beforeimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/before.png # ä¿¡å°å‰åŠéƒ¨åˆ†
    afterimg: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/after.png # ä¿¡å°ååŠéƒ¨åˆ†
  message: #ä¿¡ç¬ºæ­£æ–‡ï¼Œå¤šè¡Œæ–‡æœ¬ï¼Œå†™æ³•å¦‚ä¸‹
    - è¶ç¬¨è›‹ç«™é•¿ä¸æ³¨æ„ï¼Œ
    - æœ‰ä»€ä¹ˆæƒ³åæ§½çš„ï¼Œ
    - æˆ–è€…æƒ³å¤¸çš„(ä¸å¿…åæƒœæ–‡å­—),
    - éƒ½å¯ä»¥æ‚„å’ªå’ªå†™åœ¨è¿™é‡Œå“¦~
  bottom: Onlyy å°åŠ©æ‰‹ä¸ºæ‚¨æœåŠ¡ï¼ #ä»…æ”¯æŒå•è¡Œæ–‡æœ¬
  height: #1050pxï¼Œä¿¡å°åˆ’å‡ºçš„é«˜åº¦
  path: #ã€å¯é€‰ã€‘comments çš„è·¯å¾„åç§°ã€‚é»˜è®¤ä¸º commentsï¼Œç”Ÿæˆçš„é¡µé¢ä¸º comments/index.html
  front_matter: #ã€å¯é€‰ã€‘commentsé¡µé¢çš„ front_matter é…ç½®
    title: ç•™è¨€æ¿ğŸ’
    comments: true

# é¦–é¡µåˆ†ç±»ç£è´´
# hexo-butterfly-categories-card
# see https://akilar.top/posts/a9131002/
categoryBar:
  enable: true # å¼€å…³
  priority: 5 #è¿‡æ»¤å™¨ä¼˜å…ˆæƒ
  enable_page: / # åº”ç”¨é¡µé¢
  layout: # æŒ‚è½½å®¹å™¨ç±»å‹
    type: id
    name: recent-posts
    index: 0
  column: odd # oddï¼š3åˆ— | evenï¼š4åˆ—
  row: #æ˜¾ç¤ºè¡Œæ•°ï¼Œé»˜è®¤ä¸¤è¡Œï¼Œè¶…è¿‡è¡Œæ•°åˆ‡æ¢ä¸ºæ»šåŠ¨æ˜¾ç¤º
  message:
    - descr: å‰ç«¯æ‚çƒ©
      cover: https://assets.onlyy.vip/photos/dont-starve/bg_wendy_victorian.png
    - descr: JSæµ…æ
      cover: https://assets.onlyy.vip/photos/dont-starve/bg_goats.png
    - descr: TSåŸºç¡€ä¸è¿›é˜¶
      cover: https://assets.onlyy.vip/photos/dont-starve/bg_pigking.png
    - descr: ä¸€èµ·è¯»æºç 
      cover: https://assets.onlyy.vip/photos/dont-starve/bg_webber_feast.png
    - descr: 2022 Vue3ä¸Šæ–°
      cover: https://assets.onlyy.vip/photos/dont-starve/bg_wilson_madscience.png
    - descr: æ‚è°ˆæ•™ç¨‹
      cover: https://assets.onlyy.vip/photos/dont-starve/bg_woodie_victorian.png
  custom_css: https://npm.elemecdn.com/hexo-butterfly-categories-card@1.0.0/lib/categorybar.css

# å¤–æŒ‚æ ‡ç­¾
# tag-plugins-plus
# see https://akilar.top/posts/615e2dec/
tag_plugins:
  enable: true # å¼€å…³
  priority: 5 #è¿‡æ»¤å™¨ä¼˜å…ˆæƒ
  issues: false #issuesæ ‡ç­¾ä¾èµ–æ³¨å…¥å¼€å…³
  link:
    placeholder: /img/link.png #link_cardæ ‡ç­¾é»˜è®¤çš„å›¾æ ‡å›¾ç‰‡
  CDN:
    anima: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/font-awesome-animation.min.css #åŠ¨ç”»æ ‡ç­¾animaçš„ä¾èµ–
    jquery: https://npm.elemecdn.com/jquery@latest/dist/jquery.min.js #issuesæ ‡ç­¾ä¾èµ–
    issues: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/issues.js #issuesæ ‡ç­¾ä¾èµ–
    # iconfont: //at.alicdn.com/t/font_2032782_8d5kxvn09md.js # å·²å¤±æ•ˆ # å‚çœ‹https://akilar.top/posts/d2ebecef/
    carousel: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/carousel-touch.js
    tag_plugins_css: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/tag_plugins.css

# wow.js åŠ¨ç”»
wowjs:
  enable: true #æ§åˆ¶åŠ¨ç”»å¼€å…³ã€‚trueæ˜¯æ‰“å¼€ï¼Œfalseæ˜¯å…³é—­
  priority: 10 #è¿‡æ»¤å™¨ä¼˜å…ˆçº§
  mobile: false #ç§»åŠ¨ç«¯æ˜¯å¦å¯ç”¨ï¼Œé»˜è®¤ç§»åŠ¨ç«¯ç¦ç”¨
  animateitem:
    - class: recent-post-item #å¿…å¡«é¡¹ï¼Œéœ€è¦æ·»åŠ åŠ¨ç”»çš„å…ƒç´ çš„class
      style: animate__zoomIn #å¿…å¡«é¡¹ï¼Œéœ€è¦æ·»åŠ çš„åŠ¨ç”»
      duration: 2s #é€‰å¡«é¡¹ï¼ŒåŠ¨ç”»æŒç»­æ—¶é—´ï¼Œå•ä½å¯ä»¥æ˜¯msä¹Ÿå¯ä»¥æ˜¯sã€‚ä¾‹å¦‚3sï¼Œ700msã€‚
      delay: 1s #é€‰å¡«é¡¹ï¼ŒåŠ¨ç”»å¼€å§‹çš„å»¶è¿Ÿæ—¶é—´ï¼Œå•ä½å¯ä»¥æ˜¯msä¹Ÿå¯ä»¥æ˜¯sã€‚ä¾‹å¦‚3sï¼Œ700msã€‚
      offset: 100 #é€‰å¡«é¡¹ï¼Œå¼€å§‹åŠ¨ç”»çš„è·ç¦»ï¼ˆç›¸å¯¹æµè§ˆå™¨åº•éƒ¨ï¼‰
      iteration: 2 #é€‰å¡«é¡¹ï¼ŒåŠ¨ç”»é‡å¤çš„æ¬¡æ•°
    - class: card-widget
      style: animate__zoomIn
  animate_css: https://npm.elemecdn.com/hexo-butterfly-wowjs/lib/animate.min.css
  wow_js: https://npm.elemecdn.com/hexo-butterfly-wowjs/lib/wow.min.js
  wow_init_js: https://npm.elemecdn.com/hexo-butterfly-wowjs/lib/wow_init.js

# æ–‡ç« ç½®é¡¶æ»šåŠ¨æ 
# hexo-butterfly-swiper
# see https://akilar.top/posts/8e1264d1/
swiper:
  enable: true # å¼€å…³
  priority: 5 #è¿‡æ»¤å™¨ä¼˜å…ˆæƒ
  enable_page: all # åº”ç”¨é¡µé¢
  timemode: date #date/updated
  layout: # æŒ‚è½½å®¹å™¨ç±»å‹
    type: id
    name: recent-posts
    index: 0
  default_descr: ä½œè€…è¿˜åœ¨ç¡è§‰ï¼Œå¿˜äº†å†™æ–‡ç« æè¿°~
  swiper_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.css #swiper cssä¾èµ–
  swiper_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.js #swiper jsä¾èµ–
  custom_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiperstyle.css # é€‚é…ä¸»é¢˜æ ·å¼è¡¥ä¸
  custom_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper_init.js # swiperåˆå§‹åŒ–æ–¹æ³•
  ### åœ¨æ–‡ç« çš„ front_matter ä¸­æ·»åŠ  swiper_index é…ç½®é¡¹å³å¯ã€‚
  ### å¦‚ï¼šswiper_index: 1

# git æäº¤æ—¥å†
# hexo-filter-gitcalendar
# see https://akilar.top/posts/1f9c68c9/
# gitcalendar:
#   enable: true # å¼€å…³
#   priority: 5 #è¿‡æ»¤å™¨ä¼˜å…ˆæƒ
#   enable_page: / # åº”ç”¨é¡µé¢
#   # butterflyæŒ‚è½½å®¹å™¨
#   layout: # æŒ‚è½½å®¹å™¨ç±»å‹
#     type: id
#     name: recent-posts
#     index: 0
#   # volantisæŒ‚è½½å®¹å™¨
#   # layout:
#   #   type: class
#   #   name: l_main
#   #   index: 0
#   # materyæŒ‚è½½å®¹å™¨
#   # layout:
#   #   type: id
#   #   name: indexCard
#   #   index: 0
#   # mengdæŒ‚è½½å®¹å™¨
#   # layout:
#   #   type: class
#   #   name: content
#   #   index: 0
#   user: loveyy520 #gitç”¨æˆ·å
#   apiurl: git-calendar.onlyy.vip # è‡ªå»ºä¸€ä¸ªAPI
#   minheight:
#     pc: 280px #æ¡Œé¢ç«¯æœ€å°é«˜åº¦
#     mibile: 0px #ç§»åŠ¨ç«¯æœ€å°é«˜åº¦
#   color: "['#e4dfd7', '#f9f4dc', '#f7e8aa', '#f7e8aa', '#f8df72', '#fcd217', '#fcc515', '#f28e16', '#fb8b05', '#d85916', '#f43e06']" #æ©˜é»„è‰²è°ƒ
#   # color: "['#ebedf0', '#fdcdec', '#fc9bd9', '#fa6ac5', '#f838b2', '#f5089f', '#c4067e', '#92055e', '#540336', '#48022f', '#30021f']" #æµ…ç´«è‰²è°ƒ
#   # color: "['#ebedf0', '#f0fff4', '#dcffe4', '#bef5cb', '#85e89d', '#34d058', '#28a745', '#22863a', '#176f2c', '#165c26', '#144620']" #ç¿ ç»¿è‰²è°ƒ
#   # color: "['#ebedf0', '#f1f8ff', '#dbedff', '#c8e1ff', '#79b8ff', '#2188ff', '#0366d6', '#005cc5', '#044289', '#032f62', '#05264c']" #å¤©é’è‰²è°ƒ
#   container: .recent-post-item(style='width:100%;height:auto;padding:10px;') #çˆ¶å…ƒç´ å®¹å™¨ï¼Œéœ€è¦ä½¿ç”¨pugè¯­æ³•
#   gitcalendar_css: https://npm.elemecdn.com/hexo-filter-gitcalendar/lib/gitcalendar.css
#   gitcalendar_js: https://npm.elemecdn.com/hexo-filter-gitcalendar/lib/gitcalendar.js

# ä¾§è¾¹æ—¶é’Ÿ
# electric_clock
# see https://anzhiy.cn/posts/fc18.html
electric_clock:
  enable: true # å¼€å…³
  enable_page: all # åº”ç”¨é¡µé¢
  exclude:
    - /posts/
    - /about/
  layout: # æŒ‚è½½å®¹å™¨ç±»å‹
    type: class
    name: sticky_layout
    index: 0
  loading: https://cdn.cbd.int/hexo-butterfly-clock-anzhiyu/lib/loading.gif #åŠ è½½åŠ¨ç”»è‡ªå®šä¹‰
  clock_css: https://cdn.cbd.int/hexo-butterfly-clock-anzhiyu/lib/clock.min.css
  clock_js: https://cdn.cbd.int/hexo-butterfly-clock-anzhiyu/lib/clock.min.js
  ip_api: https://widget.qweather.net/simple/static/js/he-simple-common.js?v=2.0
  qweather_key: b71ecf86205a4d209cd76c784d236f7b # ! å’Œé£å¤©æ°”keyï¼Œè‡ªå·±ç”³è¯·çš„keyï¼Œæ¯å¤©å¯è®¿é—®1000æ¬¡
  gaud_map_key: # 861674891b4db454912180b8fb57b8ee # ! é«˜å¾—åœ°å›¾webæœåŠ¡keyï¼Œæœ€æ–°éœ€è¦æ­é…å¯†é’¥ä½¿ç”¨ï¼Œä¼¼ä¹æœ¬æ’ä»¶æš‚ä¸æ”¯æŒ
  default_rectangle: false # å¼€å¯åå°†ä¸€ç›´æ˜¾ç¤ºrectangleä½ç½®çš„å¤©æ°”ï¼Œå¦åˆ™å°†è·å–è®¿é—®è€…çš„åœ°ç†ä½ç½®ä¸å¤©æ°”
  rectangle: 112.982279,28.19409 # è·å–è®¿é—®è€…ä½ç½®å¤±è´¥æ—¶ä¼šæ˜¾ç¤ºè¯¥ä½ç½®çš„å¤©æ°”ï¼ŒåŒæ—¶è¯¥ä½ç½®ä¸ºå¼€å¯default_rectangleåçš„ä½ç½®

# æ–‡ç« åŒæ å¸ƒå±€
butterfly_article_double_row:
  enable: false

# åˆ†ç±»ç£è´´ é¦–é¡µæ˜¾ç¤ºæœ‰é—®é¢˜  æš‚æ—¶å–æ¶ˆ
## ! dark-mode æš‚æœªé€‚é…
# magnet:
#   enable: true
#   priority: 1
#   enable_page: /
#   type: categories
#   devide: 2
#   display:
#     - name: æ•™ç¨‹
#       display_name: å°å†°ã®é­”æ”¹æ•™ç¨‹
#       icon: ğŸ“š
#     - name: æ¸¸æˆè¯„æµ‹
#       display_name: å°å†°ã®æ¸¸æˆè¯„æµ‹
#       icon: ğŸ®
#     - name: ç”Ÿæ´»è¶£é—»
#       display_name: å°å†°ã®ç”Ÿæ´»è¶£é—»
#       icon: ğŸ±â€ğŸ‘“
#     - name: vue
#       display_name: å°å†°ã®ç¼–ç¨‹å­¦ä¹ 
#       icon: ğŸ‘©â€ğŸ’»
#     - name: å­¦ä¹ 
#       display_name: å°å†°ã®è¯»ä¹¦ç¬”è®°
#       icon: ğŸ“’
#     - name: éšæƒ³
#       display_name: å°å†°ã®èƒ¡æ€ä¹±æƒ³
#       icon: ğŸ’¡
#   color_setting:
#     text_color: black
#     text_hover_color: white
#     background_color: "#f2f2f2"
#     background_hover_color: "#b30070"
#   layout:
#     type: id
#     name: recent-posts
#     index: 0
#   temple_html: '<div class="recent-post-item" style="width:100%;height: auto"><div id="catalog_magnet"><a class="magnet_link_more" href="/articals/categories" style="flex:1;text-align: center;margin-bottom: 10px;" one-link-mark="yes">æ›´å¤šåˆ†ç±»...</a></div></div>'
#   plus_style: ""

# éŸ³ä¹æ’­æ”¾å™¨æ’ä»¶
aplayer:
  meting: true
  asset_inject: false # å…³é—­ asset_inject é˜²æ­¢æ³¨å…¥é‡å¤èµ„æº

# è±†ç“£æ¸…å•æ’ä»¶ï¼ˆä¸æä¾›ç«™å†…æ’­æ”¾ã€é˜…è¯»ç­‰åŠŸèƒ½ï¼‰
douban:
  user: 264246084
  builtin: true
  book:
    title: ä¹¦ç± | æ¸…å•
    quote: "è±†ç“£è¯»ä¹¦ä¸ªäººæ¸…å•ï¼Œä¸æä¾›ç«™å†…é˜…è¯»åŠŸèƒ½~"
    meta: true
    comments: true
    top_img: https://assets.onlyy.vip/photos/dont-starve/bg_wendy_victorian.png
    aside: true
    path: recommend/books
    limit:
  movie:
    title: "å½±è§† | æ¸…å•"
    quote: "è±†ç“£ç”µå½±ä¸ªäººæ¸…å•ï¼Œä¸æä¾›ç«™å†…è§‚å½±åŠŸèƒ½~"
    meta: true
    comments: true
    top_img: https://assets.onlyy.vip/photos/dont-starve/bg_wendy_victorian.png
    aside: true
    path: recommend/movies
    limit:
  timeout: 10000

# SEO æ’ä»¶
nofollow:
  enable: true
  field: site
  exclude:
    # - 'exclude1.com'
    # - 'exclude2.com'
# sitemap:
#   path:
#     - sitemap.xml
#     - sitemap.txt
#   template: ./sitemap_template.xml
#   template_txt: ./sitemap_template.txt
#   rel: false
#   tags: true
#   categories: true

baidusitemap:
path: baidusitemap.xml

# å¯ç”¨å‹ç¼©æ’ä»¶
all_minifier: true

# æ–‡ç« è®¿é—®å¯†ç é…ç½®
# encrypt
encrypt:
  pwdfile: encrypt_password # this store the password in a file, the whole content of this file will be regarded as the password
  password: 19990608 # this set password here
  replace_all_url: false # this will replace img url in all posts
  base_url: # this will connect with you img url in you post, except full url(start with http://)
  qiniu_ak: al200vzS1MXFFjYDsgaxeu1dxZPTuKMTEeNTGje4
  qiniu_sk: ayQdDabcjO1ZQjdCW9Rl6wrE0WruWePF0ktDsDyl
  img_url_ttl: 3600 # 3600 second, the ttl for qiniu img url
  type: qiniu # or base64, if base64, the base_url, qiniu_ak, qiniu_sk and img_url_ttl is unnecessary
  template: '
    <h1>æœ¬é¡µé¢ä¸å¯¹å¤–å…¬å¼€å“¦, éœ€è¦å¯†ç æ‰èƒ½é˜…è¯»~</h1>
    <h2>ps: å¦‚æœæ˜¯ä½ çš„è¯,åº”è¯¥èƒ½çŒœåˆ°è¿™ä¸ª8ä½æ•°å¯†ç ã€‚</h2>
    <input type="text" autofocus style="text-align: center;border-radius: 5px;border-style: groove;height: 30px;width: 100px;cursor: auto;font-size: 100%;font-weight: 700;margin: 0 20px 0 30%;color: #137cbd;box-shadow: #182026 1px 1px 3px;border:none;outline: none;outline: none;text-overflow: initial;">
    <input type="submit" value="ç¡® å®š" onclick="decrypt()" style="width: 58px;height: 34px;border-radius: 5px;background-color: #13b3ff;box-shadow: #182026 1px 1px 3px;border: none;color: white;">
    <div id="enc_error" style=" display: inline-block; color: #d84527; font: large; "></div>
    <script>
    const onError = function(error) {
    document.getElementById("enc_error").innerHTML = "å¯†ç ä¸å¯¹å•¦ï¼å·çœ‹åˆ«äººéšç§æ˜¯ä¸ç¤¼è²Œçš„å“¦~";
    };
    function decrypt() {
    const passwd = document.querySelector("#enc_passwd input").value;
    doDecrypt(passwd, onError);
    }
    </script>
    '
# optional, it's html template include html and js. in js, you should call doDecrypt(password, onErrorCallbackFunc) with you password

